---
## build or import coolstore images

# no ci/cd
- import_tasks: create_default_project.yml
  when: not enable_cicd

- import_tasks: build_images.yml
  vars:
    project_name: "{{ project_default }}"
  when: not enable_cicd

- name: check if coolstore is deployed in {{ project_default }}
  shell: "{{ openshift_cli }} get dc web-ui -n {{ project_default }}"
  register: default_deployed_result
  ignore_errors: true

- import_tasks: deploy_default.yml
  when: not enable_cicd and default_deployed_result|failed

# with ci/cd
- import_tasks: create_cicd_projects.yml
  when: enable_cicd

- import_tasks: build_images.yml
  vars:
    project_name: "{{ project_prod }}"
  when: enable_cicd

- import_tasks: promote_images.yml
  vars:
    from_project: "{{ project_prod }}"
  when: enable_cicd

- name: check if coolstore is deployed in {{ project_prod }}
  shell: "{{ openshift_cli }} get dc web-ui -n {{ project_prod }}"
  register: prod_deployed_result
  ignore_errors: true

- import_tasks: deploy_prod.yml
  when: enable_cicd and prod_deployed_result|failed

- name: check if coolstore is deployed in {{ project_stage }}
  shell: "{{ openshift_cli }} get dc web-ui -n {{ project_stage }}"
  register: stage_deployed_result
  ignore_errors: true
  when: enable_cicd

- import_tasks: deploy_stage.yml
  when: not disable_stage_project and stage_deployed_result|failed
  when: enable_cicd

- import_tasks: deploy_devtest.yml
  when: enable_cicd

- import_tasks: create_pipeline.yml
  when: enable_cicd
