---
- name: Deploy Coolstore Microservices Demo
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - demo_vars/msa/all

  tasks:
    - include_role:
        name: openshift_common_facts

    - import_role:
        name: openshift_coolstore
      vars:
        project_annotations: "demo=demo-msa-{{ project_suffix }}"
        hostname_suffix: "{{ apps_hostname_suffix }}"
        enable_cicd: false

    # verify database deployments
    - name: wait for database deployments to complete (succeed or fail)
      shell: "oc get pods -n {{ project_default }} -l comp-type=database | grep '\\-deploy\\s' | grep 'Running'"
      register: deployment_running
      until: deployment_running|failed
      retries: 20
      delay: 30
      ignore_errors: true
      tags: verify

    - include_tasks: verify_tasks.yml project_name={{ project_default }} selector="comp-type=database"
      tags: verify


    # verify other deployments
    - name: wait for other deployments to complete (succeed or fail)
      shell: "oc get pods -n {{ project_default }} -l comp-type!=database | grep '\\-deploy\\s' | grep 'Running'"
      register: deployment_running
      until: deployment_running|failed
      retries: 20
      delay: 30
      ignore_errors: true
      tags: verify

    - include_tasks: verify_tasks.yml project_name={{ project_default }} selector="comp-type!=database"
      tags: verify