- src: https://github.com/siamaksade/ansible-openshift-nexus.git
  name: openshift_nexus

- src: https://github.com/siamaksade/ansible-openshift-gogs.git
  name: openshift_gogs

- src: https://github.com/siamaksade/ansible-openshift-jenkins.git
  name: openshift_jenkins

- src: https://github.com/siamaksade/ansible-openshift-workshopper.git
  name: openshift_workshopper

- src: https://github.com/siamaksade/ansible-openshift-coolstore.git
  name: openshift_coolstore

- src: https://github.com/siamaksade/ansible-openshift-common-facts.git
  name: openshift_commons_facts