---
# unidle projects
- name: list deployment configs to unidle
  shell: "{{ openshift_cli }} get dc -o json -n {{ project_name }}"
  register: deploymentconfigs_list

- name: unidle all deployments in project {{ project_name }}"
  shell: "{{ openshift_cli }} scale --replicas={{ item.metadata.annotations['idling.alpha.openshift.io/previous-scale'] }} dc {{ item.metadata.name }} -n {{ project_name }}"
  with_items: "{{ deploymentconfigs_list.stdout|from_json|json_query('items') }}"
  when: >
    item.metadata.annotations is defined and 
    item.metadata.annotations['idling.alpha.openshift.io/previous-scale'] is defined and
    item.metadata.annotations['idling.alpha.openshift.io/previous-scale'] is not none and
    item.metadata.annotations['idling.alpha.openshift.io/previous-scale']|trim() != ""