---
# Deploy CoolStore Microservices
- name: check if coolstore is deployed in {{ project_name }}
  shell: "{{ openshift_cli }} get dc web-ui -n {{ project_name }}"
  register: deployed_result
  ignore_errors: true

- import_tasks: deploy.yml
  when: deployed_result | failed

- import_tasks: scale_down.yml
