---
# Configure Repos and Users
- name: check if coolstore-microservice git repository exists
  uri: 
    url: http://{{gogs_route}}/api/v1/repos/{{gogs_admin_user}}/coolstore-microservice
    user: "{{gogs_admin_user}}"
    password: "{{gogs_admin_password}}"
    force_basic_auth: true
    status_code: 200,404
  register: repo_result

- name: create coolstore-microservice git repository
  uri: 
    url: http://{{gogs_route}}/api/v1/user/repos
    method: POST
    body: '{"name": "coolstore-microservice", "private": false}'
    body_format: json
    user: "{{gogs_admin_user}}"
    password: "{{gogs_admin_password}}"
    status_code: 200,201
    force_basic_auth: true
  when: repo_result.status != 200
  
- name: create temporary git directory
  tempfile:
    state: directory
    prefix: coolstore-git
  register: git_dir
  when: repo_result.status != 200

- name: download coolstore-microservices code from GitHub
  get_url:
    url: https://github.com/{{github_account}}/coolstore-microservice/archive/{{github_ref}}.tar.gz
    dest: "{{git_dir.path}}/{{github_ref}}.tar.gz"
    mode: 0755
  when: repo_result.status != 200
  
- name: unarchive coolstore-microservices source archive
  unarchive:
    src: "{{git_dir.path}}/{{github_ref}}.tar.gz"
    dest: "{{git_dir.path}}"
  when: repo_result.status != 200

- name: push coolstore-microservice to git repository in Gogs
  shell: |
    mv {{git_dir.path}}/coolstore-microservice-{{github_ref}}/* {{git_dir.path}}
    rm -rf {{git_dir.path}}/coolstore-microservice-{{github_ref}}
    git init
    git remote add origin http://{{gogs_route}}/{{gogs_admin_user}}/coolstore-microservice.git
    git add . --all
    git config user.email "developer@redhat.com"
    git config user.name "developer"
    git commit -m "Initial add"
    git push -f http://{{gogs_admin_user}}:{{gogs_admin_password}}@{{gogs_route}}/{{gogs_admin_user}}/coolstore-microservice.git master
  args:
    chdir: "{{git_dir.path}}"
  when: repo_result.status != 200

- name: check if developer user exists
  uri: 
    url: http://{{gogs_route}}/api/v1/users/{{gogs_user}}
    user: "{{gogs_admin_user}}"
    password: "{{gogs_admin_password}}"
    force_basic_auth: true
    status_code: 200,404
  register: user_result

- name: create developer user
  uri: 
    url: http://{{gogs_route}}/api/v1/admin/users
    method: POST
    body: "{'login_name': '{{gogs_user}}', 'username': '{{gogs_user}}', 'email': '{{gogs_user}}@gogs.com', 'password': '{{gogs_password}}'}"
    body_format: json
    user: "{{gogs_admin_user}}"
    password: "{{gogs_admin_password}}"
    status_code: 200,201
    force_basic_auth: true
  when: user_result.status != 200

