---
## Deploy Gogs Git Server
- name: deploy Gogs from template
  shell: "oc new-app -f https://raw.githubusercontent.com/OpenShiftDemos/gogs-openshift-docker/master/openshift/gogs-persistent-template.yaml --param=HOSTNAME={{gogs_route}} --param=GOGS_VERSION={{gogs_image_version}} --param=SKIP_TLS_VERIFY=true -n {{desired_project}}"
  when: not ephemeral

- name: deploy Gogs from template
  shell: "oc new-app -f https://raw.githubusercontent.com/OpenShiftDemos/gogs-openshift-docker/master/openshift/gogs-template.yaml --param=HOSTNAME={{gogs_route}} --param=GOGS_VERSION={{gogs_image_version}} --param=SKIP_TLS_VERIFY=true -n {{desired_project}}"
  when: ephemeral

- name: wait for Gogs PostgreSQL to be running
  shell: "oc get dc/gogs-postgresql -o yaml -n {{desired_project}}"
  register: result
  until: '"availableReplicas: 1" in result.stdout'
  retries: 5
  delay: 60

- name: wait for Gogs to be running
  shell: "oc get dc/gogs -o yaml -n {{desired_project}}"
  register: result
  until: '"availableReplicas: 1" in result.stdout'
  retries: 5
  delay: 60

- name: create Gogs admin user
  uri: 
    url: http://{{gogs_route}}/user/sign_up
    method: POST
    body: "user_name={{gogs_admin_user}}&password={{gogs_admin_password}}&&retype={{gogs_admin_password}}&&email={{gogs_admin_user}}@gogs.com"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: 302