---
# remove persistent storage from project
- name: list deployment configs
  shell: "{{ openshift_cli }} get dc -o json -n {{ project_name }}"
  register: deploymentconfigs_list

- name: delete pvc and dc volumes
  shell: |
    {{ openshift_cli }} volumes dc/{{ item.0.metadata.name }} --name={{ item.1.name }} --add -t emptyDir --overwrite -n {{ project_name }}
    {{ openshift_cli }} delete pvc {{ item.1.persistentVolumeClaim.claimName }} -n {{ project_name }}
  with_subelements: 
    - "{{ deploymentconfigs_list.stdout|from_json|json_query('items[?spec.template.spec.volumes]') }}"
    - spec.template.spec.volumes
  when: >
    ephemeral and 
    item.1.persistentVolumeClaim is defined and 
    item.1.persistentVolumeClaim is not none and 
    item.1.persistentVolumeClaim|trim() != ""

- name: list deployment configs that use database
  shell: "{{ openshift_cli }} get dc -o json -n {{ project_name }}"
  register: deploymentconfigs_with_database_list

- name: restart deployments that use database to re-init databases
  shell: "{{ openshift_cli }} rollout latest dc/{{ item.metadata.name }} -n {{ project_name }}"
  with_items: deploymentconfigs_with_database_list|from_json|json_query('items')
  when: ephemeral



