---
## Sonatype Nexus Install
- name: check if nexus exists
  shell: "{{ openshift_cli }} get service nexus -n {{ project_name }}"
  register: install_nexus
  ignore_errors: true

- name: deploy nexus template
  shell: "{{ openshift_cli }} new-app -f https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/nexus{{ nexus_version }}-persistent-template.yaml --param=VOLUME_CAPACITY={{ nexus_volume_capacity }} --param=MAX_MEMORY={{ nexus_max_memory }} --param=NEXUS_VERSION={{ nexus_image_version }} -n {{ project_name }}"
  when: (install_nexus | failed) and (not ephemeral)

- name: deploy nexus template
  shell: "{{ openshift_cli }} new-app -f https://raw.githubusercontent.com/OpenShiftDemos/nexus/master/nexus{{ nexus_version }}-template.yaml --param=MAX_MEMORY={{ nexus_max_memory }} --param=NEXUS_VERSION={{ nexus_image_version }} -n {{ project_name }}"
  when: (install_nexus | failed) and ephemeral

- name: set nexus route fact
  set_fact:
    nexus_route: "{{ 'nexus-' + project_name + '.' + apps_hostname_suffix }}"

- name: wait for nexus to be running
  uri:
    url: http://{{ nexus_route }}
    status_code: 200
  register: result
  until: result.status == 200
  retries: 10
  delay: 30