---
deployments_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/coolstore-deployments-template.yaml
netflix_oss_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/netflix-oss-list.yaml
bluegreen_deployment_template: https://raw.githubusercontent.com/{{ github_account }}/coolstore-microservice/{{ github_ref }}/openshift/templates/inventory-bluegreen-template.yaml

image_version: latest

enable_bluegreen: false
enable_netflix: false

# delete dc using this selector to scale the environment down
# prune_by_selector: 

# scale down dc using this selector to scale the environment down
# scale_down_by_selector:
