---
# Promote CoolStore Images
- name: list image streams
  shell: "{{ openshift_cli }} get is -o json -n {{ from_project }}"
  register: is_list

- name: tag images in {{ to_project }}
  shell: "{{ openshift_cli }} tag {{ from_project }}/{{ item.metadata.name }}:latest {{ to_project }}/{{ item.metadata.name }}:{{ tag }}"
  with_items: "{{ is_list.stdout|from_json|json_query('items') }}"
  when: item|json_query("status.tags[?tag=='latest']")|trim() != '[]'

- name: tag inventory blue/green images in {{ to_project }}
  shell: "{{ openshift_cli }} tag {{ from_project }}/{{ bluegreen_image }}:latest {{ to_project }}/{{ bluegreen_image }}:{{ tag }}-{{ item }}"
  with_items: [ "green", "blue"]
  when: >
    bluegreen_image is defined and 
    bluegreen_image is not none and 
    bluegreen_image|trim() != ""