---
- name: Deploy Coolstore Microservices Demo
  hosts: localhost
  gather_facts: false
  run_once: true
  roles:
    - coolstore_projects
    - { role: nexus, project_name: "{{ project_cicd }}", when: maven_mirror_url is none or maven_mirror_url == '' }
    - { role: gogs, project_name: "{{ project_cicd }}", gogs_hostname: "{{ apps_hostname }}" }
    - { role: coolstore_deploy, project_name: "{{ project_cicd }}", apps_hostname: "{{ apps_hostname }}" }
